specfile_path: python3-sabrtooth.spec
upstream_package_name: sABRTooth-python
upstream_project_url: https://github.com/abrt/sABRTooth-python
downstream_package_name: python-sabrtooth
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
